### ISSUE TITLE
 Can I run the GHICP.exe directly? Or how should I do to use your code?

### ISSUE THREAD

**Issue by coldcoda** [YuePanEdward/GH-ICP#3]
Hello @YuePanEdward , I am learning how to registrate and stich point clouds together.
So can I run the GHICP.exe directly? Or how should I do to use your code?

And, when I run the GHICP.exe and appear an error:
![image](https://user-images.githubusercontent.com/37976152/58238707-5827db80-7d7a-11e9-927f-86edadcf225e.png)
Should I install VTK to solve this problem? 

I really need your help. I want to get a complete head module with stitching the multiple point clouds together!
Thanks a lot!!

**Comment by YuePanEdward** [comment]
Sorry for being late.
Now there's a cross-template version. The errors have been fixed. 
Thanks.
