### ISSUE TITLE
wrong result

### ISSUE THREAD

**Issue by caoxudong0513** [YuePanEdward/GH-ICP#7]
**hi,it is a nice work!
i run this example use this  script:**
#data path
target_point_cloud_path=/home/arch/s1.ply;
source_point_cloud_path=/home/arch/s2.ply;
output_point_cloud_path=/home/arch/reg_s2.pcd;

#parameters
using_feature=B;              # Feature selection [ B: BSC, F: FPFH, R: RoPS, N: register without feature ]
corres_estimation_method=N;   # Correspondence estimation by [ K: Bipartite graph min weight match using KM, N: Nearest Neighbor, R: Reciprocal NN ]

downsample_resolution=0.1;    # Raw data downsampling voxel size, just keep one point in the voxel  
neighborhood_radius=0.5;      # Curvature estimation / feature encoding radius
curvature_non_max_radius=1.0; # Keypoint extraction based on curvature: non max suppression radius 
weight_adjustment_ratio=1.1;  # Weight would be adjusted if the IoU between expected value and calculated value is beyond this value
weight_adjustment_step=0.1;   # Weight adjustment for one iteration
registration_dof=6;           # Degree of freedom of the transformation [ 4: TLS with leveling, 6: arbitary ]
appro_overlap_ratio=0.5;      # Estimated approximate overlapping ratio of two point cloud 

launch_realtime_viewer=1;     # Launch the realtime registration viewer during registration or not (1: Launch, 0: Not launch)

#run
./bin/ghicp ${target_point_cloud_path} ${source_point_cloud_path} ${output_point_cloud_path} \
${using_feature} ${corres_estimation_method} \
${downsample_resolution} ${neighborhood_radius} ${curvature_non_max_radius} \
${weight_adjustment_ratio} ${weight_adjustment_step} ${registration_dof} ${appro_overlap_ratio} ${launch_realtime_viewer}

**then i get wrong reslut,
Final transformation matrix:
-0.0911522  -0.957878   0.272338   -2.22012
 -0.995763   0.091092 -0.0128938    1.41576
-0.0124568  -0.272358  -0.962119     1.1656
         0          0          0          1
A pcd file has been exported
Click X(close) to continue...

groundtruth is:
0.9317582977 0.3630790644 0.0002599753 -10.5909217645
-0.3630791504 0.9317581820 0.0004699465 -9.2871497734
-0.0000716063 -0.0005322681 0.9999998558 0.8096312993
0.0000000000 0.0000000000 0.0000000000 1.0000000000
can i how to do next?
thank you**

**Comment by monage2018** [comment]
change corres_estimation_method to K?

**Comment by caoxudong0513** [comment]
> change corres_estimation_method to K?

it is also wrong. i download the datasets from 
https://prs.igp.ethz.ch/research/completed_projects/automatic_registration_of_point_clouds.html

Arch (ZIP, 873 MB): Typical dataset to acuqire data of an object of interest (here: Roman arch). 5 Scans are placed around the arch. The scans are acquired with rather low overlap (30-​40%) and feature vegetation and artifacts (moving people).

**Comment by monage2018** [comment]
Hi, I download the datasets you point out above. Here is my result:
Final transformation matrix:
   0.936942    0.349468 -0.00398849    -10.2015
  -0.349489    0.936909 -0.00814224    -9.22895
  0.0008915  0.00902258    0.999959    0.687552
          0           0           0           1
521.102s (CPU)
 the results is accurate
Here is my config:
#parameters
using_feature=B;              # Feature selection [ B: BSC, F: FPFH, R: RoPS, N: register without feature ]
corres_estimation_method=K;   # Correspondence estimation by [ K: Bipartite graph min weight match using KM, N: Nearest Neighbor, R: Reciprocal NN ]

downsample_resolution=0.1;    # Raw data downsampling voxel size, just keep one point in the voxel  
neighborhood_radius=0.3;      # Curvature estimation / feature encoding radius
curvature_non_max_radius=1.0; # Keypoint extraction based on curvature: non max suppression radius 
weight_adjustment_ratio=1.1;  # Weight would be adjusted if the IoU between expected value and calculated value is beyond this value
weight_adjustment_step=0.1;   # Weight adjustment for one iteration
registration_dof=6;           # Degree of freedom of the transformation [ 4: TLS with leveling, 6: arbitary ]
appro_overlap_ratio=0.5;      # Estimated approximate overlapping ratio of two point cloud 

launch_realtime_viewer=1;     # Launch the realtime registration viewer during registration or not (1: Launch, 0: Not launch)

**Comment by monage2018** [comment]
What program do you use?You build GH-ICP with CMake by yourself, or you just use the original version available on Windows provided by the author? I advise you build it by yourself.That's what i did.

**Comment by caoxudong0513** [comment]
> What program do you use?You build GH-ICP with CMake by yourself, or you just use the original version available on Windows provided by the author? I advise you build it by yourself.That's what i did.

thank you for your reply
I build GH-ICP with CMake by myself in my computer (ubuntu16.04)
and i try again using your config .
The result is
0.937002   -0.349323  0.00068333     6.33185
   0.349305     0.93697  0.00878227     12.2081
-0.00370821 -0.00799067     0.99996   -0.804177
          0           0           0           1
**But** the displayed result in viewer looks correct. Do you know what this is about?

**Comment by caoxudong0513** [comment]
![Screenshot from 2020-03-19 15-12-25](https://user-images.githubusercontent.com/24645601/77042640-ff0af180-69f6-11ea-96d7-ed436d58cf51.png)

**Comment by monage2018** [comment]
Hi,I think you might set s1 as the target point cloud and s2 as the source point cloud. i'm right?

**Comment by monage2018** [comment]
Then you should watch the ground_truth s2-s1.tfm

**Comment by caoxudong0513** [comment]
> Then you should watch the ground_truth s2-s1.tfm

You are right! 
Thank you !
