### ISSUE TITLE
result is not good

### ISSUE THREAD

**Issue by improve100** [YuePanEdward/GH-ICP#9]
i try use it.my config is:
using_feature=B;              # Feature selection [ B: BSC, F: FPFH, R: RoPS, N: register without feature ]
corres_estimation_method=N;   # Correspondence estimation by [ K: Bipartite graph min weight match using KM, N: Nearest Neighbor, R: Reciprocal NN ]

downsample_resolution=0.01;    # Raw data downsampling voxel size, just keep one point in the voxel  
neighborhood_radius=0.3;      # Curvature estimation / feature encoding radius
curvature_non_max_radius=1.0; # Keypoint extraction based on curvature: non max suppression radius 
weight_adjustment_ratio=1.1;  # Weight would be adjusted if the IoU between expected value and calculated value is beyond this value
weight_adjustment_step=0.1;   # Weight adjustment for one iteration
registration_dof=6;           # Degree of freedom of the transformation [ 4: TLS with leveling, 6: arbitary ]
appro_overlap_ratio=0.5;      # Estimated approximate overlapping ratio of two point cloud 

launch_realtime_viewer=1;     # Launch the realtime registration viewer during registration or not (1: Launch, 0: Not launch)

the result:
![2020-05-12 13-54-31屏幕截图](https://user-images.githubusercontent.com/6092914/81647875-4eeabf80-9460-11ea-9354-0c1f3e81fc41.png)
![image](https://user-images.githubusercontent.com/6092914/81648055-a12be080-9460-11ea-979a-f7b9190c8233.png)

**Comment by improve100** [comment]
How to constrain matching results only x y z yaw??

**Comment by YuePanEdward** [comment]
Sorry for the late reply. You can set registration_dof=4 in the configuration file to constrain the results on only x,y,z and yaw.
